package com.mpp.rental.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.LocalDateTime;

/**
 * Stores Firebase Cloud Messaging (FCM) tokens per user per browser/device.
 * Phase 2: enables push notifications even when browser is closed.
 *
 * One user can have multiple tokens (e.g. logged in on Chrome + Firefox).
 * Tokens are removed on logout and refreshed on next login.
 */
@Entity
@Table(name = "fcm_token")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class FcmToken {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "token_id")
    private Long tokenId;

    /**
     * The user this token belongs to
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    /**
     * FCM registration token from the browser
     * Generated by Firebase SDK on the frontend
     */
    @Column(name = "fcm_token", nullable = false, length = 500)
    private String fcmToken;

    /**
     * Optional: browser/device identifier for debugging
     * e.g. "Chrome on Windows", "Firefox on Mac"
     */
    @Column(name = "device_info", length = 255)
    private String deviceInfo;

    /**
     * Whether this token is still active
     * Set to false on logout or when FCM returns invalid-token error
     */
    @Column(name = "is_active", nullable = false)
    private Boolean isActive = true;

    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @UpdateTimestamp
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;
}